# Generated by Django 4.1.4 on 2022-12-30 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('téléphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commande_Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('téléphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type_Produit',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='app1.type_produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande_un_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_produit', to='app1.commande_produits')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_produit', to='app1.produit')),
            ],
        ),
    ]
