# Generated by Django 4.1.4 on 2022-12-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_un_produit',
            name='commande',
        ),
        migrations.AddField(
            model_name='commande_produits',
            name='produit_commander',
            field=models.ManyToManyField(related_name='list_des_commande', to='app1.commande_un_produit'),
        ),
    ]
