# Generated by Django 4.1.4 on 2022-12-28 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='nom_prenom',
        ),
        migrations.RenameField(
            model_name='fournisseur',
            old_name='nom',
            new_name='nom_prenom',
        ),
    ]
