# Generated by Django 4.1.4 on 2022-12-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_commande_un_produit_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_un_produit',
            name='commande',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='commande_produit', to='app1.commande_produits'),
            preserve_default=False,
        ),
    ]
