# Generated by Django 4.1.4 on 2022-12-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_commande_un_produit_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande_un_produit',
            name='commande',
        ),
    ]
