# Generated by Django 4.1.4 on 2023-01-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_commande_un_produit_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheter_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('unité_HT', models.PositiveIntegerField()),
                ('montant_HT', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achete_produit', to='app1.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('Num_Doc', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to='app1.fournisseur')),
                ('produit_achat', models.ManyToManyField(related_name='des_produits_acheter', to='app1.acheter_produit')),
            ],
        ),
    ]
