# Generated by Django 4.1.4 on 2023-01-03 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_acheter_produit_montant_ht_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheter_produit',
            name='montant_HT',
        ),
        migrations.CreateModel(
            name='BL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TVA', models.PositiveIntegerField(default=19)),
                ('remise', models.PositiveIntegerField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bl_facture', to='app1.facture')),
            ],
        ),
    ]
