# Generated by Django 4.1.4 on 2023-01-04 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_acheter_produit_montant_ht_bl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commande_Produits',
            new_name='Bon_Cammande',
        ),
    ]
