# Generated by Django 4.1.4 on 2023-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_commande_produits_bon_cammande'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='facture',
            field=models.ManyToManyField(null=True, related_name='fourner_de_factuers', to='app1.facture'),
        ),
    ]
