# Generated by Django 4.1.4 on 2023-01-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_fournisseur_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='facture',
            field=models.ManyToManyField(blank=True, related_name='fourner_de_factuers', to='app1.facture'),
        ),
    ]
