# Generated by Django 4.1.4 on 2023-01-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_fournisseur_facture_fournisseur_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourner_de_factuers', to='app1.facture'),
        ),
    ]
