# Generated by Django 4.1.4 on 2023-01-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_fournisseur_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='facture',
        ),
    ]
