# Generated by Django 4.1.4 on 2023-01-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_fournisseur_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vente_un_produit', to='app1.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_vente', to='app1.client')),
                ('list_produits', models.ManyToManyField(related_name='des_produit_vente', to='app1.vente_produit')),
            ],
        ),
    ]
