# Generated by Django 4.1.4 on 2023-01-12 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_acheter_produit_prix_vente_stock_credit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
