# Generated by Django 4.1.4 on 2023-01-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='prix_vente',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='unité_HT',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
